architect-checklist:
  checklist_file: docs/checklists/architect-checklist.md
  required_docs:
    - architecture.md
  default_locations:
    - docs/architecture.md

platform-engineer-checklist:
  checklist_file: docs/checklists/infrastructure-checklist.md
  required_docs:
    - platform-architecture.md
  default_locations:
    - docs/platform-architecture.md

frontend-architecture-checklist:
  checklist_file: docs/checklists/frontend-architecture-checklist.md
  required_docs:
    - frontend-architecture.md
  default_locations:
    - docs/frontend-architecture.md
    - docs/fe-architecture.md

pm-checklist:
  checklist_file: docs/checklists/pm-checklist.md
  required_docs:
    - prd.md
  default_locations:
    - docs/prd.md

po-master-checklist:
  checklist_file: docs/checklists/po-master-checklist.md
  required_docs:
    - prd.md
    - architecture.md
  optional_docs:
    - frontend-architecture.md
  default_locations:
    - docs/prd.md
    - docs/frontend-architecture.md
    - docs/architecture.md

story-draft-checklist:
  checklist_file: docs/checklists/story-draft-checklist.md
  required_docs:
    - story.md
  default_locations:
    - docs/stories/*.md

story-dod-checklist:
  checklist_file: docs/checklists/story-dod-checklist.md
  required_docs:
    - story.md
  default_locations:
    - docs/stories/*.md


qa-testing-checklist:
  checklist_file: docs/checklists/qa-testing-checklist.md
  required_docs:
    - story.md
  default_locations:
    - docs/stories/*.md
    - docs/test-plans/*.md

devops-deployment-checklist:
  checklist_file: docs/checklists/devops-deployment-checklist.md
  required_docs:
    - infra-deployment.md
  default_locations:
    - docs/infra-deployment.md
    - docs/deployment/*.md

data-science-checklist:
  checklist_file: docs/checklists/data-science-checklist.md
  required_docs:
    - data-models.md
  default_locations:
    - docs/data-models.md
    - docs/ml-models/*.md

